services:
  # === FastAPI (основное приложение) ===
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtbank_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
      - ./api:/app/api
      - ./test_data:/app/test_data
      - ./test_results:/app/test_results
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/v1
    depends_on:
      - ollama
    restart: unless-stopped

  # === OpenWebUI ===
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "9090:8080"
    volumes:
      - openwebui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  # === Ollama ===
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_local
    ports:
      - "11435:11434"
    volumes:
      - rag_ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  openwebui:
  rag_ollama_data:
    external: true